posts/urls.py
from django.urls import path
from . import views

app_name ="posts"

urlpatterns = [
    path("", views.PostView, name="posts"),
    path("liked/", views.LikeUnlike, name="liked-posts"),
]

socialbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("profiles/", include('profiles.urls', namespace='profiles')),
    path("posts/", include('posts.urls', namespace='posts')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
from django.utils import timezone
import math


class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to="posts", validators=[
                              FileExtensionValidator(["png", "jpg", "jpeg", "gif"])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name="likes")
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="posts")

    def __str__(self):
        return f"{self.content[:20]}"

    def whenpublished(self):
        now = timezone.now()
        
        diff= now - self.created

        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            seconds= diff.seconds
            
            if seconds == 1:
                return str(seconds) +  "second ago"
            
            else:
                return str(seconds) + " seconds ago"

            

        if diff.days == 0 and diff.seconds >= 60 and diff.seconds < 3600:
            minutes= math.floor(diff.seconds/60)

            if minutes == 1:
                return str(minutes) + " minute ago"
            
            else:
                return str(minutes) + " minutes ago"



        if diff.days == 0 and diff.seconds >= 3600 and diff.seconds < 86400:
            hours= math.floor(diff.seconds/3600)

            if hours == 1:
                return str(hours) + " hour ago"

            else:
                return str(hours) + " hours ago"

        # 1 day to 30 days
        if diff.days >= 1 and diff.days < 30:
            days= diff.days
        
            if days == 1:
                return str(days) + " day ago"

            else:
                return str(days) + " days ago"

        if diff.days >= 30 and diff.days < 365:
            months= math.floor(diff.days/30)
            

            if months == 1:
                return str(months) + " month ago"

            else:
                return str(months) + " months ago"


        if diff.days >= 365:
            years= math.floor(diff.days/365)

            if years == 1:
                return str(years) + " year ago"

            else:
                return str(years) + " years ago"

    def num_likes(self):
        return self.liked.all()

    def num_comments(self):
        return self.comment_set.all()

    class Meta:
        ordering = ('-created',)



class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=255, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


class Like(models.Model):

    LIKE_CHOICES = (
        ("Like", "Like"),
        ("Unlike", "Unlike"),
    )

    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(max_length=8, choices=LIKE_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"
    

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostModelForm(ModelForm):

    class Meta:
        model = Post
        fields = ('content', 'image',)


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from profiles.models import Profile
from django.shortcuts import redirect, render
from .models import Post, Like 
from .forms import PostModelForm, CommentForm


def PostView(request):
    qs = Post.objects.all()
    profile = Profile.objects.get(user=request.user)

    post_form = PostModelForm()
    comment_form = CommentForm()
    post_added = False

    if "submit_p_form" in request.POST:
        post_form = PostModelForm(request.POST, request.FILES)
    
        if post_form.is_valid():
            instance = post_form.save(commit=False)
            instance.author = profile
            instance.save()
            post_form = PostModelForm()
            post_added = True
            

    if "submit_c_form" in request.POST:
        comment_form = CommentForm(request.POST)
    
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            comment_form = CommentForm()


    context = {
        "qs": qs,
        "profile": profile,
        "post_form": post_form,
        "comment_form": comment_form,
        "post_added": post_added,
    }
    return render(request, "main.html", context)


def LikeUnlike(request):
    user = request.user
    if request.method == "POST":
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)
        
        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value=="Like":
                like.value ="Unlike"
            else:
                like.value = "Like"

            post_obj.save()
            like.save()

    return redirect("posts:posts")

posts/templates/posts/comment-post.html
{% extends "base.html" %}

{% block content %}


<!-- component -->
<div class="flex justify-center items-start h-full absolute top-0 w-full mt-7">
    <button type="button" onclick="openModal('mymodalcentered')" class="px-4 py-2 bg-blue-500 text-white rounded mr-3">Open Modal Centered</button>
</div>


<dialog id="mymodalcentered" class="bg-transparent z-0 relative w-screen h-screen">
    <div class="p-7 flex justify-center items-center fixed left-0 top-0 w-full h-full bg-gray-900 bg-opacity-50 z-50 transition-opacity duration-300 opacity-0">
        <div class="bg-gray-50 dark:bg-black p-10 flex items-center justify-center">
        <div class="bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-800 p-4 rounded-xl border max-w-xl">
            <div class="flex justify-between">
                <div class="flex items-center">
                    
                    <div class="ml-1.5 text-sm leading-tight">
                        <span class="text-black dark:text-white font-bold block ">Visualize Value</span>
                        <span class="text-gray-500 dark:text-gray-400 font-normal block">@visualizevalue</span>
                    </div>
                </div>
                <svg class="text-blue-400 dark:text-white h-6 w-auto inline-block fill-current" viewBox="0 0 24 24"><g><path d="M23.643 4.937c-.835.37-1.732.62-2.675.733.962-.576 1.7-1.49 2.048-2.578-.9.534-1.897.922-2.958 1.13-.85-.904-2.06-1.47-3.4-1.47-2.572 0-4.658 2.086-4.658 4.66 0 .364.042.718.12 1.06-3.873-.195-7.304-2.05-9.602-4.868-.4.69-.63 1.49-.63 2.342 0 1.616.823 3.043 2.072 3.878-.764-.025-1.482-.234-2.11-.583v.06c0 2.257 1.605 4.14 3.737 4.568-.392.106-.803.162-1.227.162-.3 0-.593-.028-.877-.082.593 1.85 2.313 3.198 4.352 3.234-1.595 1.25-3.604 1.995-5.786 1.995-.376 0-.747-.022-1.112-.065 2.062 1.323 4.51 2.093 7.14 2.093 8.57 0 13.255-7.098 13.255-13.254 0-.2-.005-.402-.014-.602.91-.658 1.7-1.477 2.323-2.41z"></path></g></svg>
                </div>
                <p class="text-black dark:text-white block text-xl leading-snug mt-3">“No one ever made a decision because of a number. They need a story.” — Daniel Kahneman</p>
                <img class="mt-2 rounded-2xl border border-gray-100 dark:border-gray-700" src="https://pbs.twimg.com/media/EpkuplDXEAEjbFc?format=jpg&name=medium"/>
                <p class="text-gray-500 dark:text-gray-400 text-base py-1 my-0.5">10:05 AM · Dec 19, 2020</p>
                <div class="border-gray-200 dark:border-gray-600 border border-b-0 my-1"></div>
                <div class="text-gray-500 dark:text-gray-400 flex mt-3">
                <div class="flex items-center mr-6">
                    <svg class="fill-current h-5 w-auto" viewBox="0 0 24 24" class="r-1re7ezh r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr" style=""><g><path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12zM7.354 4.225c-2.08 0-3.903 1.988-3.903 4.255 0 5.74 7.034 11.596 8.55 11.658 1.518-.062 8.55-5.917 8.55-11.658 0-2.267-1.823-4.255-3.903-4.255-2.528 0-3.94 2.936-3.952 2.965-.23.562-1.156.562-1.387 0-.014-.03-1.425-2.965-3.954-2.965z"></path></g></svg>
                    <span class="ml-3">615</span>
                </div>
                <div class="flex items-center mr-6">
                    <svg class="fill-current h-5 w-auto" viewBox="0 0 24 24" class="r-1re7ezh r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"><g><path d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z"></path></g></svg>
                    <span class="ml-3">93 people are Tweeting about this</span>
                </div>
            </div>
        </div>
    </div>
    </div>
</dialog>



<script>
    function openModal(key) {
        document.getElementById(key).showModal(); 
        document.body.setAttribute('style', 'overflow: hidden;'); 
        document.getElementById(key).children[0].scrollTop = 0; 
        document.getElementById(key).children[0].classList.remove('opacity-0'); 
        document.getElementById(key).children[0].classList.add('opacity-100')
    }

    function modalClose(key) {
        document.getElementById(key).children[0].classList.remove('opacity-100');
        document.getElementById(key).children[0].classList.add('opacity-0');
        setTimeout(function () {
            document.getElementById(key).close();
            document.body.removeAttribute('style');
        }, 100);
    }
</script>


{% endblock content %}

posts/templates/posts/create-post.html
{% extends "base.html" %}

{% block content %}


<div class="bg-gray-50 dark:bg-black mb-2 flex items-center justify-center">
  <div class="bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-800 p-4 rounded-xl border max-w-xl">
    <form action="" method="post" enctype="multipart/form-data">
        <div class="flex justify-between">
            <div class="inset-1">
                <img class="h-11 w-11 rounded-full" src="https://pbs.twimg.com/profile_images/1287562748562309122/4RLk5A_U_x96.jpg"/>
            </div>
        <div class="items-center w-full">
            <div class="ml-1.5 text-sm leading-tight">
                
                    {% csrf_token %}
                    {{post_form.as_p}}
                
            </div>
        </div>
        </div>
        <div class="text-gray-500 dark:text-gray-400 flex mt-3">
        <div class="flex items-center mr-6">
            <svg class="fill-current h-5 w-auto" viewBox="0 0 24 24" class="r-1re7ezh r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr" style=""><g><path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12zM7.354 4.225c-2.08 0-3.903 1.988-3.903 4.255 0 5.74 7.034 11.596 8.55 11.658 1.518-.062 8.55-5.917 8.55-11.658 0-2.267-1.823-4.255-3.903-4.255-2.528 0-3.94 2.936-3.952 2.965-.23.562-1.156.562-1.387 0-.014-.03-1.425-2.965-3.954-2.965z"></path></g></svg>
            <span class="ml-3">615</span>
        </div>
        <div class="flex items-center mr-6">
            <svg class="fill-current h-5 w-auto" viewBox="0 0 24 24" class="r-1re7ezh r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"><g><path d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z"></path></g></svg>
            <span class="ml-3">93</span>
        </div>
        <div>
            <button type="submit" name="submit_p_form" class="mr-auto">
                Post
            </button>
        </div>
        </div>
    </form>
  </div>
</div>




{% endblock content %}

posts/templates/posts/post.html
{% extends "base.html" %}

{% block content %}

	{% for post in qs %}

		<div class="dark:bg-black p-2 -mt-2 flex flex-grow items-center justify-center">
			<div class="w-full bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-800 p-4 rounded-xl border max-w-xl">
				<div class="flex justify-between">
					<div class="flex items-center">
						<img class="h-11 w-11 rounded-full" src="https://pbs.twimg.com/profile_images/1287562748562309122/4RLk5A_U_x96.jpg"/>
						<div class="ml-1.5 text-sm leading-tight">
							<span class="text-black dark:text-white font-bold block ">Symaxx Digital</span>
							<span class="text-gray-500 dark:text-gray-400 font-normal block">@symaxx</span>
						</div>
					</div>
					<svg class="text-blue-400 dark:text-white h-6 w-auto inline-block fill-current" viewBox="0 0 24 24"><g><path d="M23.643 4.937c-.835.37-1.732.62-2.675.733.962-.576 1.7-1.49 2.048-2.578-.9.534-1.897.922-2.958 1.13-.85-.904-2.06-1.47-3.4-1.47-2.572 0-4.658 2.086-4.658 4.66 0 .364.042.718.12 1.06-3.873-.195-7.304-2.05-9.602-4.868-.4.69-.63 1.49-.63 2.342 0 1.616.823 3.043 2.072 3.878-.764-.025-1.482-.234-2.11-.583v.06c0 2.257 1.605 4.14 3.737 4.568-.392.106-.803.162-1.227.162-.3 0-.593-.028-.877-.082.593 1.85 2.313 3.198 4.352 3.234-1.595 1.25-3.604 1.995-5.786 1.995-.376 0-.747-.022-1.112-.065 2.062 1.323 4.51 2.093 7.14 2.093 8.57 0 13.255-7.098 13.255-13.254 0-.2-.005-.402-.014-.602.91-.658 1.7-1.477 2.323-2.41z"></path></g></svg>
				</div>
				<p class="text-black dark:text-white block text-xl leading-snug mt-3">{{post.content}}</p>
				{% if post.image %}
				<img class="mt-2 rounded-2xl border h-40 border-gray-100 dark:border-gray-700" src="{{post.image.url}}" alt=""/>
				{% else %}
				{% endif %}
				<p class="text-gray-500 dark:text-gray-400 text-base py-1 my-0.5">{{post.whenpublished}}</p>
				<div class="border-gray-200 dark:border-gray-600 border border-b-0 my-1"></div>
				<div class="text-gray-500 dark:text-gray-400 flex mt-3">
					<form action="{% url "posts:liked-posts" %}" method="post">
						{% csrf_token %}
						<div class="flex items-center mr-6">
							<input type="hidden" name="post_id" id="" value="{{post.id}}">
							{% if profile not in post.liked.all %}
								<button type="submit">
									<svg class="fill-current h-6 w-auto" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
									width="50" height="50"
									viewBox="0 0 172 172"
									style=" fill:#fa314a;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#666666"><path d="M51.6,24.08c-24.65781,0 -44.72,20.06219 -44.72,44.72c0,50.78031 57.43188,75.84125 76.97,92.1275l2.15,1.8275l2.15,-1.8275c19.53813,-16.28625 76.97,-41.34719 76.97,-92.1275c0,-24.65781 -20.06219,-44.72 -44.72,-44.72c-13.94812,0 -26.20312,6.62469 -34.4,16.6625c-8.19687,-10.03781 -20.45187,-16.6625 -34.4,-16.6625zM51.6,30.96c13.19563,0 24.725,6.7725 31.4975,16.985l2.9025,4.3l2.9025,-4.3c6.7725,-10.2125 18.30188,-16.985 31.4975,-16.985c20.93563,0 37.84,16.90438 37.84,37.84c0,44.37063 -49.5575,67.33531 -72.24,85.2475c-22.6825,-17.91219 -72.24,-40.87687 -72.24,-85.2475c0,-20.93562 16.90438,-37.84 37.84,-37.84z"></path></g></g></svg>
								</button>
							{% else %}

								<button>
									<img class="h-6" src="https://img.icons8.com/ios-filled/50/fa314a/like--v1.png"/>
								</button>

							{% endif %}
							<span class="ml-3">{{post.num_likes.count}}</span>
						</div>
					</form>
					<div class="flex items-center mr-6">
						<button onclick="openModal('mymodaltop')" name="submit_p_form">
							<svg class="fill-current h-6 w-auto" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
							width="50" height="50"
							viewBox="0 0 172 172"
							style=" fill:#fa314a;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#666666"><path d="M86,20.64c39.82875,0 72.24,27.76188 72.24,61.89313c0,34.13125 -32.41125,61.90656 -72.24,61.90656c-6.08719,0 -12.01312,-0.69875 -18.11375,-2.12312l-4.07156,-0.95406l-2.72781,3.17125c-2.35156,2.75469 -10.25281,10.84406 -23.28719,13.115c2.48594,-4.48812 4.36719,-9.05687 5.60344,-13.62562c0.95406,-3.56094 1.12875,-5.42875 1.1825,-7.05469l0.16125,-3.84312l-3.18469,-2.15c-17.67031,-11.94594 -27.80219,-29.60281 -27.80219,-48.44219c0,-34.13125 32.41125,-61.89313 72.24,-61.89313M86,13.76c-43.59125,0 -79.12,30.54344 -79.12,68.77313c0,22.19875 12.1475,41.52187 30.82563,54.13969c-0.02688,0.73906 0.02687,1.94844 -0.95406,5.54969c-1.19594,4.47469 -3.64156,10.76344 -8.58656,17.85844l-3.52062,5.03906h6.14094c21.29844,0 33.62062,-13.88094 35.52875,-16.11156c6.3425,1.49156 12.87312,2.31125 19.68594,2.31125c43.59125,0 79.12,-30.54344 79.12,-68.78656c0,-38.22969 -35.52875,-68.77313 -79.12,-68.77313z"></path></g></g></svg>
						</button>
						<span class="ml-3">93 people are Tweeting about this</span>
					</div>
				</div>
			</div>
		</div>

		<dialog id="mymodaltop" class="bg-transparent z-0 relative w-screen h-screen">
			<div class="p-7 flex justify-center items-start overflow-x-hidden overflow-y-auto fixed left-0 top-0 w-full h-full bg-gray-900 bg-opacity-50 z-50 transition-opacity duration-300 opacity-0">
				<div class="bg-white flex rounded-lg w-1/2 relative">
					<div class="flex flex-col items-start">
						<div class="p-2 flex items-center w-full">	
							<svg onclick="modalClose('mymodaltop')" class="ml-auto fill-current text-gray-700 w-5 h-5 cursor-pointer" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
								<path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z" />
							</svg>
						</div>

							<!--Add the content here-->
							<form action="" method="post"> 
								{% csrf_token %}
								<input type="hidden" name="post_id" value={{post.id}}>
								{{comment_form.as_p}}

								<button type="submit" name="submit_c_form">Comment</button>
							</form>
							{% if post.comment_set.all %}

								{% for comment in post.comment_set.all %}
									<ul>
										<li>
										<p class="">{{ comment.body }}</p>
										</li>
									</ul>
								{% endfor %}
							
							{% else %}
							{% endif %}
					</div>
				</div>
			</div>
		</dialog>

		

		
	
	{% endfor %}

{% endblock content %}

{% block script %}

	<script>
		function openModal(key) {
			document.getElementById(key).showModal(); 
			document.body.setAttribute('style', 'overflow: hidden;'); 
			document.getElementById(key).children[0].scrollTop = 0; 
			document.getElementById(key).children[0].classList.remove('opacity-0'); 
			document.getElementById(key).children[0].classList.add('opacity-100')
		}

		function modalClose(key) {
			document.getElementById(key).children[0].classList.remove('opacity-100');
			document.getElementById(key).children[0].classList.add('opacity-0');
			setTimeout(function () {
				document.getElementById(key).close();
				document.body.removeAttribute('style');
			}, 100);
		}
	</script>

{% endblock script %}